### PR TITLE
Create not_found_page.dart

### PR DESCRIPTION
**Pull request by jayakrishna352**

### CODE REVIEW

**Comment by skytect** [comment]
Hi @jayakrishna352 , thanks for the help! May I check where you got the gif from, in case there's any licensing issues?

**Comment by jayakrishna352** [comment]
> Hi @jayakrishna352 , thanks for the help! May I check where you got the gif from, in case there's any licensing issues?

**Comment by jayakrishna352** [comment]
> Hi @jayakrishna352 , thanks for the help! May I check where you got the gif from, in case there's any licensing issues?
I found this gif link in a codebase of some developer using codepen.io under css pane (https://codepen.io/Navedkhan012/pen/vrWQMY).

https://cdn.dribbble.com/users/285475/screenshots/2083086/dribbble_1.gif

**Comment by skytect** [comment]
Hmm I don't think we can use that as it is stated in https://dribbble.com/terms that
> All Content uploaded are copyright © their respective owners.

**Pull request closed without merging**
